- hosts: ubuntu1
  gather_facts: false
  vars:
    test1: "Bye World"
  tasks:
  - name: Ansible when variable contains string example example
    debug:
      msg: "Equals"
    when: test1.find("World") != -1