- hosts: ubuntu1
  gather_facts: false
  tasks:
  - shell: cat /home/vagrant/temp.txt
    register: output
  - name: Ansible when variable contains string example example
    debug:
      msg: "Equals"
    when: output.stdout.find("World") != -1   