---
- name: Get Service Status
  hosts: ubuntu1
  become: true

  tasks:
  - name: collect facts about system services
    service_facts:
    register: my_var

  - name: Debug
    debug:
      var: my_var